<h4><?php echo __('Lastest Comment For Post ID =') . $block->getPostId() ?></h4>
<ul class="blog-post-list">
    <?php
        echo "<pre>";
        var_dump($block->getComments()->getData());
        echo "</pre>";
        foreach ($block->getComments() as $cmt)
        {
    ?>
        <li class="blog-post-list-item">
            <a href=""><?php echo $cmt->getAuthor() ?></a>

            <div class="blog-post-item-content">
                <?php echo $cmt->getContent() ?>
            </div>

            <div class="blog-post-item-meta">
                <small><?php echo __('Created at: ') ?> <?php echo $cmt->getCreationTime() ?></small>
            </div>

        </li>
    <?php } ?>
</ul>