<h4><?php echo __('Lastest Comment For Post ID =') . $block->getPostId() ?></h4>
<?php
//    print_r($block->getIdentities());
//    die();
?>
<ul class="blog-comment-list">
    <h1>Comments is active</h1>
    <?php
//        echo "<pre>";
//        var_dump($block->getComments()->getData());
//        echo "</pre>";
        foreach ($block->getComments() as $cmt)
        {
    ?>
        <li class="blog-post-list-item">
            <a href=""><?php echo $cmt->getAuthor() ?></a>

            <div class="blog-post-item-content">
                <?php echo $cmt->getContent() ?>
            </div>

            <div class="blog-post-item-meta">
                <small><?php echo __('Created at: ') ?> <?php echo $cmt->getCreationTime() ?></small>
            </div>

            <div class="blog-post-item-email">
                <?php echo $cmt->getEmail() ?>
            </div>

        </li>
    <?php } ?>
</ul>