<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="absolute-footer" style="text-align:center;">
    <p>
        [Part4_PluginPractice]:
        <?php if($customer) echo $customer->getFirstname(); ?>
    </p>
    <p>
        <?php
            if (!$customer->isEmpty()) echo 'Customer is logged in';
        ?>
    </p>
    <?php /* @escapeNotVerified */
        echo $block->getMiscellaneousHtml();
    ?>
</div>
